server:
  address: 0.0.0.0
  port: 8080
  host: steve-think

spring:
  application:
    name: formulaforecast

  datasource:
    url: jdbc:postgresql://localhost:5432/formulaforecast
    username: formulaforecast
    password: formulaforecast
    driver-class-name: org.postgresql.Driver

  flyway:
    default-schema: public
    url: jdbc:postgresql://localhost:5432/formulaforecast
    user: formulaforecast
    password: formulaforecast
    driver-class-name: org.postgresql.Driver

  security:
    jwt:
      secret-key: supersecretkey
      expiration-time: 3600000


  quartz:
    job-store-type: memory

auth:
  cookies:
    domain: localhost
    secure: true
    same-site: None
    http-only: true