server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: formulaforecast


  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    default-schema: public
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration-time: 3600000

cors:
  allowed-origins:
    - https://demo.formulaforecast.com

  quartz:
    job-store-type: memory

auth:
  cookies:
    domain: formulaforecast.com
    secure: true
    same-site: None
    http-only: true