server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: formulaforecast

  datasource:
    url: jdbc:postgresql://formulaforecastdemo.cv2wkmkwm2lk.eu-west-2.rds.amazonaws.com/formulaforecast
    username: formulaforecast
    password: Ec3z75bXWUgrw3eoGv1z
    driver-class-name: org.postgresql.Driver

  flyway:
    default-schema: public
    url: jdbc:postgresql://formulaforecastdemo.cv2wkmkwm2lk.eu-west-2.rds.amazonaws.com/formulaforecast
    user: formulaforecast
    password: Ec3z75bXWUgrw3eoGv1z
    driver-class-name: org.postgresql.Driver

  security:
    jwt:
      secret-key: ac3af2fb1d2b58e9bcf0ddd6815804ca047ed64222c64aad76bb223b9112ec91
      expiration-time: 3600000


  quartz:
    job-store-type: memory
