-- Baseline schema. Replaces the original V1-V28 migration history.
--
-- Conventions: every table has a surrogate BIGINT id used for foreign keys and a UUID used by the API.
-- Every foreign key column is indexed, either by its own index or as the leading column of a unique constraint.

-- Seasons ------------------------------------------------------------------------------------------------------------

CREATE TABLE championship_season (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    championship_season_uid UUID NOT NULL,
    championship_year TEXT NOT NULL,
    championship_name TEXT NOT NULL,

    CONSTRAINT pk_championship_season_id PRIMARY KEY (id),
    CONSTRAINT uk_championship_season_championship_season_uid UNIQUE (championship_season_uid),
    CONSTRAINT uk_championship_season_championship_year UNIQUE (championship_year),
    CONSTRAINT ck_championship_season_championship_year CHECK (championship_year ~ '^[0-9]{4}$')
);

-- Race weekends ------------------------------------------------------------------------------------------------------

CREATE TABLE race_weekend (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    race_weekend_uid UUID NOT NULL,
    championship_season_id BIGINT NOT NULL,
    round_number INTEGER NOT NULL,
    race_name TEXT NOT NULL,
    race_location TEXT NOT NULL,
    -- Local calendar dates at the circuit, used for display and the weekend status job.
    race_weekend_start_date DATE NOT NULL,
    race_weekend_end_date DATE NOT NULL,

    CONSTRAINT pk_race_weekend_id PRIMARY KEY (id),
    CONSTRAINT uk_race_weekend_race_weekend_uid UNIQUE (race_weekend_uid),
    -- Deferred so a season can be renumbered by start date in a single statement when a weekend is added.
    CONSTRAINT uk_race_weekend_season_round UNIQUE (championship_season_id, round_number) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT fk_race_weekend_championship_season_id FOREIGN KEY (championship_season_id) REFERENCES championship_season (id),
    CONSTRAINT ck_race_weekend_round_number CHECK (round_number > 0),
    CONSTRAINT ck_race_weekend_dates CHECK (race_weekend_end_date >= race_weekend_start_date)
);

CREATE TABLE race_weekend_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    race_weekend_session_uid UUID NOT NULL,
    race_weekend_id BIGINT NOT NULL,
    session_type TEXT NOT NULL,
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_race_weekend_session_id PRIMARY KEY (id),
    CONSTRAINT uk_race_weekend_session_race_weekend_session_uid UNIQUE (race_weekend_session_uid),
    CONSTRAINT uk_race_weekend_session_one_per_type UNIQUE (race_weekend_id, session_type),
    CONSTRAINT fk_race_weekend_session_race_weekend_id FOREIGN KEY (race_weekend_id) REFERENCES race_weekend (id) ON DELETE CASCADE,
    CONSTRAINT ck_race_weekend_session_session_type CHECK (session_type IN (
        'PRACTICE_1', 'PRACTICE_2', 'PRACTICE_3', 'SPRINT_QUALIFYING', 'SPRINT', 'QUALIFYING', 'RACE'))
);

CREATE TABLE race_weekend_current_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    race_weekend_id BIGINT NOT NULL,
    event_time TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT NOT NULL,

    CONSTRAINT pk_race_weekend_current_status_id PRIMARY KEY (id),
    CONSTRAINT uk_race_weekend_current_status_race_weekend_id_status UNIQUE (race_weekend_id),
    CONSTRAINT fk_race_weekend_current_status_race_weekend_id FOREIGN KEY (race_weekend_id) REFERENCES race_weekend (id) ON DELETE CASCADE,
    CONSTRAINT ck_race_weekend_current_status_status CHECK (status IN ('UPCOMING', 'RACE_WEEK', 'LIVE', 'COMPLETE'))
);

-- Only one weekend at a time can be in race week or live.
CREATE UNIQUE INDEX uk_race_weekend_current_status_race_week ON race_weekend_current_status (status) WHERE status = 'RACE_WEEK';
CREATE UNIQUE INDEX uk_race_weekend_current_status_live ON race_weekend_current_status (status) WHERE status = 'LIVE';

CREATE TABLE race_weekend_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    race_weekend_id BIGINT NOT NULL,
    event_time TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT NOT NULL,

    CONSTRAINT pk_race_weekend_status_history_id PRIMARY KEY (id),
    CONSTRAINT fk_race_weekend_status_history_race_weekend_id FOREIGN KEY (race_weekend_id) REFERENCES race_weekend (id) ON DELETE CASCADE,
    CONSTRAINT ck_race_weekend_status_history_status CHECK (status IN ('UPCOMING', 'RACE_WEEK', 'LIVE', 'COMPLETE'))
);

CREATE INDEX ix_race_weekend_status_history_race_weekend_id ON race_weekend_status_history (race_weekend_id);

-- Drivers and constructors -------------------------------------------------------------------------------------------

CREATE TABLE driver (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    driver_uid UUID NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    nickname TEXT NOT NULL,
    date_of_birth DATE NOT NULL,
    nationality TEXT NOT NULL,

    CONSTRAINT pk_driver_id PRIMARY KEY (id),
    CONSTRAINT uk_driver_driver_uid UNIQUE (driver_uid)
);

CREATE TABLE constructor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    constructor_uid UUID NOT NULL,
    team_name TEXT NOT NULL,
    base TEXT NOT NULL,

    CONSTRAINT pk_constructor_id PRIMARY KEY (id),
    CONSTRAINT uk_constructor_constructor_uid UNIQUE (constructor_uid)
);

-- A driver's constructor for a season. A driver with no row for a season is not on the grid that season.
CREATE TABLE driver_constructor_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    championship_season_id BIGINT NOT NULL,
    driver_id BIGINT NOT NULL,
    constructor_id BIGINT NOT NULL,

    CONSTRAINT pk_driver_constructor_mapping_id PRIMARY KEY (id),
    CONSTRAINT uk_driver_constructor_mapping_unique_season_driver UNIQUE (championship_season_id, driver_id),
    CONSTRAINT fk_driver_constructor_mapping_championship_season_id FOREIGN KEY (championship_season_id) REFERENCES championship_season (id),
    CONSTRAINT fk_driver_constructor_mapping_driver_id FOREIGN KEY (driver_id) REFERENCES driver (id),
    CONSTRAINT fk_driver_constructor_mapping_constructor_id FOREIGN KEY (constructor_id) REFERENCES constructor (id)
);

CREATE INDEX ix_driver_constructor_mapping_driver_id ON driver_constructor_mapping (driver_id);
CREATE INDEX ix_driver_constructor_mapping_constructor_id ON driver_constructor_mapping (constructor_id);

-- Accounts and teams -------------------------------------------------------------------------------------------------

CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_uid UUID NOT NULL,
    email TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone_number TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    password TEXT NOT NULL,

    CONSTRAINT pk_account_id PRIMARY KEY (id),
    CONSTRAINT uk_account_account_uid UNIQUE (account_uid),
    CONSTRAINT uk_account_email UNIQUE (email),
    CONSTRAINT uk_account_phone_number UNIQUE (phone_number)
);

CREATE TABLE user_team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    team_uid UUID NOT NULL,
    account_id BIGINT NOT NULL,
    team_name TEXT NOT NULL,
    team_colour TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_user_team_id PRIMARY KEY (id),
    CONSTRAINT uk_user_team_team_uid UNIQUE (team_uid),
    CONSTRAINT uk_user_team_account_id UNIQUE (account_id),
    CONSTRAINT fk_user_team_account_id FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE
);

-- Team names are unique regardless of case.
CREATE UNIQUE INDEX uk_user_team_team_name ON user_team (lower(team_name));

-- Leaderboards -------------------------------------------------------------------------------------------------------

CREATE TABLE championship_leaderboard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    championship_leaderboard_uid UUID NOT NULL,
    championship_season_id BIGINT NOT NULL,
    championship_leaderboard_name TEXT NOT NULL,
    owner_account_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    leaderboard_type TEXT NOT NULL,

    CONSTRAINT pk_championship_leaderboard_id PRIMARY KEY (id),
    CONSTRAINT uk_championship_leaderboard_leaderboard_uid UNIQUE (championship_leaderboard_uid),
    CONSTRAINT uk_championship_leaderboard_season_name UNIQUE (championship_season_id, championship_leaderboard_name),
    CONSTRAINT fk_championship_leaderboard_championship_season_id FOREIGN KEY (championship_season_id) REFERENCES championship_season (id),
    CONSTRAINT fk_championship_leaderboard_owner_account_id FOREIGN KEY (owner_account_id) REFERENCES account (id),
    CONSTRAINT ck_championship_leaderboard_leaderboard_user_owner CHECK (
        (leaderboard_type = 'USER' AND owner_account_id IS NOT NULL)
        OR (leaderboard_type IN ('GLOBAL_DEFAULT', 'SYSTEM') AND owner_account_id IS NULL))
);

CREATE UNIQUE INDEX ux_ch_leaderboard_one_global_per_season
    ON championship_leaderboard (championship_season_id)
    WHERE leaderboard_type = 'GLOBAL_DEFAULT';
CREATE INDEX ix_championship_leaderboard_owner_account_id ON championship_leaderboard (owner_account_id);

CREATE TABLE championship_leaderboard_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    championship_leaderboard_entrant_uid UUID NOT NULL,
    user_team_id BIGINT NOT NULL,
    championship_leaderboard_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_championship_leaderboard_entrant_id PRIMARY KEY (id),
    CONSTRAINT uk_championship_leaderboard_entrant_uid UNIQUE (championship_leaderboard_entrant_uid),
    CONSTRAINT uk_entrant_user_team_leaderboard_id UNIQUE (user_team_id, championship_leaderboard_id),
    CONSTRAINT fk_championship_leaderboard_entrant_user_team_id FOREIGN KEY (user_team_id) REFERENCES user_team (id) ON DELETE CASCADE,
    CONSTRAINT fk_championship_leaderboard_entrant_championship_leaderboard_id FOREIGN KEY (championship_leaderboard_id) REFERENCES championship_leaderboard (id)
);

CREATE INDEX ix_championship_leaderboard_entry_championship_leaderboard_id ON championship_leaderboard_entry (championship_leaderboard_id);

-- Predictions --------------------------------------------------------------------------------------------------------

CREATE TABLE prediction_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    prediction_type_uid UUID NOT NULL,
    prediction_type TEXT NOT NULL,
    description TEXT NOT NULL,
    prediction_selection_type TEXT NOT NULL,
    -- How many ranked picks a prediction of this type takes: 1 for a single driver, 3 for a top three.
    selection_count INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_prediction_type_id PRIMARY KEY (id),
    CONSTRAINT uk_prediction_prediction_type_uid UNIQUE (prediction_type_uid),
    CONSTRAINT uk_prediction_prediction_type UNIQUE (prediction_type),
    CONSTRAINT ck_prediction_type_prediction_selection_type CHECK (prediction_selection_type IN ('DRIVER')),
    CONSTRAINT ck_prediction_type_selection_count CHECK (selection_count BETWEEN 1 AND 3)
);

-- One team's prediction of one type for one weekend. Points stay null until a result for the type is entered.
CREATE TABLE prediction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    prediction_uid UUID NOT NULL,
    prediction_type_id BIGINT NOT NULL,
    user_team_id BIGINT NOT NULL,
    race_weekend_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    points INTEGER,
    scored_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT pk_prediction_id PRIMARY KEY (id),
    CONSTRAINT uk_prediction_prediction_uid UNIQUE (prediction_uid),
    CONSTRAINT uk_prediction_unique_user_team_prediction_type_per_race_weekend UNIQUE (user_team_id, race_weekend_id, prediction_type_id),
    CONSTRAINT fk_prediction_prediction_type_id FOREIGN KEY (prediction_type_id) REFERENCES prediction_type (id),
    CONSTRAINT fk_prediction_user_team_id FOREIGN KEY (user_team_id) REFERENCES user_team (id) ON DELETE CASCADE,
    CONSTRAINT fk_prediction_race_weekend_id FOREIGN KEY (race_weekend_id) REFERENCES race_weekend (id),
    CONSTRAINT ck_prediction_points CHECK (points >= 0),
    CONSTRAINT ck_prediction_scored CHECK ((points IS NULL) = (scored_at IS NULL))
);

CREATE INDEX ix_prediction_race_weekend_id_prediction_type_id ON prediction (race_weekend_id, prediction_type_id);
CREATE INDEX ix_prediction_prediction_type_id ON prediction (prediction_type_id);

-- The picks in a prediction. Single driver predictions have one pick at rank 1.
CREATE TABLE prediction_choice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    prediction_choice_uid UUID NOT NULL,
    prediction_id BIGINT NOT NULL,
    driver_id BIGINT NOT NULL,
    rank INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_prediction_choice_id PRIMARY KEY (id),
    CONSTRAINT uk_prediction_choice_prediction_choice_uid UNIQUE (prediction_choice_uid),
    CONSTRAINT uk_prediction_choice_prediction_rank UNIQUE (prediction_id, rank),
    CONSTRAINT uk_prediction_choice_prediction_driver UNIQUE (prediction_id, driver_id),
    CONSTRAINT fk_prediction_choice_prediction_id FOREIGN KEY (prediction_id) REFERENCES prediction (id) ON DELETE CASCADE,
    CONSTRAINT fk_prediction_choice_driver_id FOREIGN KEY (driver_id) REFERENCES driver (id),
    CONSTRAINT ck_prediction_choice_rank CHECK (rank >= 1)
);

CREATE INDEX ix_prediction_choice_driver_id ON prediction_choice (driver_id);

-- Results ------------------------------------------------------------------------------------------------------------

-- The actual outcome of one prediction type for one weekend, entered by an admin.
CREATE TABLE prediction_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    prediction_result_uid UUID NOT NULL,
    race_weekend_id BIGINT NOT NULL,
    prediction_type_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_prediction_result_id PRIMARY KEY (id),
    CONSTRAINT uk_prediction_result_prediction_result_uid UNIQUE (prediction_result_uid),
    CONSTRAINT uk_prediction_result_race_weekend_prediction_type UNIQUE (race_weekend_id, prediction_type_id),
    CONSTRAINT fk_prediction_result_race_weekend_id FOREIGN KEY (race_weekend_id) REFERENCES race_weekend (id),
    CONSTRAINT fk_prediction_result_prediction_type_id FOREIGN KEY (prediction_type_id) REFERENCES prediction_type (id)
);

CREATE INDEX ix_prediction_result_prediction_type_id ON prediction_result (prediction_type_id);

-- The drivers in a result. Ranks may repeat to record a tie, e.g. two drivers sharing the most overtakes.
CREATE TABLE prediction_result_choice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    prediction_result_id BIGINT NOT NULL,
    driver_id BIGINT NOT NULL,
    rank INTEGER NOT NULL,

    CONSTRAINT pk_prediction_result_choice_id PRIMARY KEY (id),
    CONSTRAINT uk_prediction_result_choice_result_driver UNIQUE (prediction_result_id, driver_id),
    CONSTRAINT fk_prediction_result_choice_prediction_result_id FOREIGN KEY (prediction_result_id) REFERENCES prediction_result (id) ON DELETE CASCADE,
    CONSTRAINT fk_prediction_result_choice_driver_id FOREIGN KEY (driver_id) REFERENCES driver (id),
    CONSTRAINT ck_prediction_result_choice_rank CHECK (rank >= 1)
);

CREATE INDEX ix_prediction_result_choice_driver_id ON prediction_result_choice (driver_id);
