package com.steve.formulaforecast.service.leaderboard;

public enum LeaderboardType {
    // The global default leaderboard that all users join for the current championship season
    GLOBAL_DEFAULT,
    // A leaderboard generated by the system for a specific championship season that all users can join freely
    SYSTEM,
    // A leaderboard created by a user which they can invite other users to
    USER
}
