CREATE TABLE driver (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	driver_uid UUID NOT NULL,
	first_name TEXT NOT NULL,
	last_name TEXT NOT NULL,
	nickname TEXT NOT NULL,
	date_of_birth DATE NOT NULL,
	nationality TEXT NOT NULL,

	CONSTRAINT pk_driver_id PRIMARY KEY (id),
	CONSTRAINT uk_driver_driver_uid UNIQUE (driver_uid)
);

CREATE TABLE constructor (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	constructor_uid UUID NOT NULL,
	team_name TEXT NOT NULL,
	base TEXT NOT NULL,

	CONSTRAINT pk_constructor_id PRIMARY KEY (id),
	CONSTRAINT uk_constructor_constructor_uid UNIQUE (constructor_uid)
);

CREATE TABLE driver_constructor_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    season TEXT NOT NULL,
    constructor_id BIGINT NOT NULL,
    driver_id BIGINT NOT NULL,

    CONSTRAINT pk_driver_constructor_mapping_id PRIMARY KEY (id)
)