CREATE TABLE public.championship_season (
    	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    	championship_season_uid UUID NOT NULL,
    	championship_year TEXT NOT NULL,
    	championship_name TEXT NOT NULL,

    	CONSTRAINT pk_championship_season_id PRIMARY KEY (id),
    	CONSTRAINT uk_championship_season_championship_season_uid UNIQUE (championship_season_uid)
);

INSERT INTO public.championship_season (championship_season_uid, championship_year, championship_name)
    VALUES ('79c4bd1a-3cdb-46f4-a3cc-11ab2587af6e', '2025', '2025 Formula One World Championship');


ALTER TABLE public.race_weekend ADD COLUMN championship_season_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE public.race_weekend ADD CONSTRAINT fk_race_weekend_championship_season_id FOREIGN KEY(championship_season_id) REFERENCES championship_season(id);