CREATE TABLE race_weekend_current_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    race_weekend_status_uid UUID NOT NULL,
    race_weekend_id BIGINT NOT NULL,
    event_time TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT NOT NULL,

    CONSTRAINT pk_race_weekend_current_status_id PRIMARY KEY (id),
    CONSTRAINT fk_race_weekend_current_status_race_weekend_id FOREIGN KEY(race_weekend_id) REFERENCES race_weekend(id),
    CONSTRAINT uk_race_weekend_current_status_race_weekend_status_uid UNIQUE (race_weekend_status_uid),
    CONSTRAINT uk_race_weekend_current_status_race_weekend_id_status UNIQUE (race_weekend_id, status)
);

CREATE TABLE race_weekend_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    race_weekend_status_uid UUID NOT NULL,
    race_weekend_id BIGINT NOT NULL,
    event_time TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT NOT NULL,

    CONSTRAINT pk_race_weekend_status_history_id PRIMARY KEY (id),
    CONSTRAINT fk_race_weekend_status_history_race_weekend_id FOREIGN KEY(race_weekend_id) REFERENCES race_weekend(id)
)