CREATE TABLE public.account (
    	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    	account_uid UUID NOT NULL,
    	email TEXT NOT NULL,
    	first_name TEXT NOT NULL,
    	last_name TEXT NOT NULL,
    	phone_number TEXT,
    	created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    	password TEXT NOT NULL,

    	CONSTRAINT pk_account_id PRIMARY KEY (id),
    	CONSTRAINT uk_account_account_uid UNIQUE (account_uid),
    	CONSTRAINT uk_account_email UNIQUE (email),
    	CONSTRAINT uk_account_phone_number UNIQUE (phone_number)
);