CREATE TABLE public.user_team (
    	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    	team_uid UUID NOT NULL,
    	team_name TEXT NOT NULL,
    	team_colour TEXT NOT NULL,
    	account_uid UUID NOT NULL,
    	created_at TIMESTAMP WITH TIME ZONE NOT NULL,

    	CONSTRAINT pk_user_team_id PRIMARY KEY (id),
    	CONSTRAINT uk_user_team_team_uid UNIQUE (team_uid),
    	CONSTRAINT uk_user_team_team_name UNIQUE (team_name),
    	CONSTRAINT uk_user_team_account_uid UNIQUE (account_uid)
);