CREATE TABLE public.championship_leaderboard (
    	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    	championship_leaderboard_uid UUID NOT NULL,
    	championship_season_id BIGINT NOT NULL,
    	championship_leaderboard_name TEXT NOT NULL,
    	owner_account_id BIGINT,
    	created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    	leaderboard_type TEXT NOT NULL,

    	CONSTRAINT pk_championship_leaderboard_id PRIMARY KEY (id),
    	CONSTRAINT uk_championship_leaderboard_leaderboard_uid UNIQUE (championship_leaderboard_uid),
    	CONSTRAINT uk_championship_leaderboard_championship_leaderboard_name UNIQUE (championship_leaderboard_name),
    	CONSTRAINT fk_championship_leaderboard_championship_season_id FOREIGN KEY(championship_season_id) REFERENCES championship_season(id),
    	CONSTRAINT fk_championship_leaderboard_owner_account_id FOREIGN KEY(owner_account_id) REFERENCES account(id),
        CONSTRAINT ck_championship_leaderboard_leaderboard_user_owner CHECK (
            (leaderboard_type = 'USER' AND owner_account_id IS NOT NULL)
            OR (leaderboard_type IN ('GLOBAL_DEFAULT','SYSTEM') AND owner_account_id IS NULL)
          )
);

CREATE UNIQUE INDEX ux_ch_leaderboard_one_global_per_season
    ON championship_leaderboard (championship_season_id)
    WHERE leaderboard_type = 'GLOBAL_DEFAULT'