CREATE TABLE public.championship_leaderboard_entry (
    	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    	championship_leaderboard_entrant_uid UUID NOT NULL,
    	user_team_id BIGINT NOT NULL,
    	championship_leaderboard_id BIGINT NOT NULL,
    	created_at TIMESTAMP WITH TIME ZONE NOT NULL,

    	CONSTRAINT pk_championship_leaderboard_entrant_id PRIMARY KEY (id),
    	CONSTRAINT uk_championship_leaderboard_entrant_uid UNIQUE (championship_leaderboard_entrant_uid),
    	CONSTRAINT fk_championship_leaderboard_entrant_user_team_id FOREIGN KEY(user_team_id) REFERENCES user_team(id),
    	CONSTRAINT fk_championship_leaderboard_entrant_championship_leaderboard_id FOREIGN KEY(championship_leaderboard_id) REFERENCES championship_leaderboard(id),
    	CONSTRAINT uk_entrant_user_team_leaderboard_id UNIQUE (user_team_id, championship_leaderboard_id)
);