CREATE TABLE prediction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    prediction_uid UUID NOT NULL,
    prediction_type TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,

    CONSTRAINT pk_prediction_id PRIMARY KEY (id),
    CONSTRAINT uk_prediction_prediction_uid UNIQUE (prediction_uid),
    CONSTRAINT uk_prediction_title UNIQUE (title)
);

CREATE TABLE driver_prediction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    driver_prediction_uid UUID NOT NULL,
    prediction_id BIGINT NOT NULL,
    user_team_id BIGINT NOT NULL,
    driver_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    race_weekend_id BIGINT NOT NULL,

    CONSTRAINT pk_driver_prediction_id PRIMARY KEY (id),
    CONSTRAINT uk_driver_prediction_driver_prediction_uid UNIQUE (driver_prediction_uid),
    CONSTRAINT fk_driver_prediction_prediction_id FOREIGN KEY(prediction_id) REFERENCES prediction(id),
    CONSTRAINT fk_driver_prediction_user_team_id FOREIGN KEY(user_team_id) REFERENCES user_team(id),
    CONSTRAINT fk_driver_prediction_driver_id FOREIGN KEY(driver_id) REFERENCES driver(id),
    CONSTRAINT fk_driver_prediction_race_weekend_id FOREIGN KEY(race_weekend_id) REFERENCES race_weekend(id),
    CONSTRAINT uk_driver_prediction_unique_per_team_per_prediction UNIQUE (prediction_id, user_team_id)
);