CREATE TABLE practice_session (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	practice_session_uid UUID NOT NULL,
	race_weekend_id BIGINT NOT NULL,
	session_date DATE NOT NULL,

	CONSTRAINT pk_practice_session_id PRIMARY KEY (id),
	CONSTRAINT uk_practice_session_practice_session_uid UNIQUE (practice_session_uid),
	CONSTRAINT fk_practice_session_race_weekend_id FOREIGN KEY(race_weekend_id) REFERENCES race_weekend(id)

);

CREATE TABLE sprint_session (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	sprint_session_uid UUID NOT NULL,
	race_weekend_id BIGINT NOT NULL,
	session_date DATE NOT NULL,

	CONSTRAINT pk_sprint_session_id PRIMARY KEY (id),
	CONSTRAINT uk_sprint_session_sprint_session_uid UNIQUE (sprint_session_uid),
	CONSTRAINT fk_sprint_session_race_weekend_id FOREIGN KEY(race_weekend_id) REFERENCES race_weekend(id)
);

CREATE TABLE qualifying_session (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	qualifying_session_uid UUID NOT NULL,
	race_weekend_id BIGINT NOT NULL,
	session_date DATE NOT NULL,

	CONSTRAINT pk_qualifying_session_id PRIMARY KEY (id),
	CONSTRAINT uk_qualifying_session_qualifying_session_uid UNIQUE (qualifying_session_uid),
	CONSTRAINT fk_qualifying_session_race_weekend_id FOREIGN KEY(race_weekend_id) REFERENCES race_weekend(id)
);

CREATE TABLE race_session (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	race_session_uid UUID NOT NULL,
	race_weekend_id BIGINT NOT NULL,
	session_date DATE NOT NULL,

	CONSTRAINT pk_race_session_id PRIMARY KEY (id),
	CONSTRAINT uk_race_session_race_session_uid UNIQUE (race_session_uid),
	CONSTRAINT fk_race_session_race_weekend_id FOREIGN KEY(race_weekend_id) REFERENCES race_weekend(id)
)